# This file intentionally left blank
RETRO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
LEADER_ENABLE = yes
MOUSEKEY_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RGB_MATRIX_ENABLE = yes # For advanced RGB effects
RGB_MATRIX_EFFECTS = yes
RGB_MATRIX_EXTRA_EFFECTS = yes
RGB_MATRIX_SOLID_REACTIVE_NEXUS_ENABLE = yes
RGB_MATRIX_KEYREACTIVE_ENABLE = yes
RGB_MATRIX_STARLIGHT = yes
SRC += features/autocorrection.c
LTO_ENABLE = yes
